-- BACKUP CREATED: $(Get-Date)
-- This is a backup of your FCDS database before making image URL changes
-- Location: d:\FCDS\Web\FCDS Project new\backup_FCDS_$(Get-Date -Format 'yyyy-MM-dd_HHmmss').sql

-- To restore this backup, run:
-- psql -U postgres -d FCDS -f "path/to/this/backup/file.sql"

-- BACKUP IN PROGRESS - DO NOT EDIT THIS FILE
